default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mutterapp_development

test:
  <<: *default
  database: mutterapp_test

production:
  <<: *default
  database: mutterapp_production
  username: mutterapp
  password: <%= ENV['MUTTERAPP_DATABASE_PASSWORD'] %>
